# Generated by Django 5.2.4 on 2025-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
