# Generated by Django 5.2.4 on 2025-07-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_buku_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genre'),
        ),
        migrations.AlterField(
            model_name='perpustakaan',
            name='alamat_perpustakaan',
            field=models.TextField(),
        ),
    ]
