# Generated by Django 5.2.4 on 2025-07-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_buku_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buku_genre', to='api.genre'),
        ),
    ]
