# Generated by Django 5.2.4 on 2025-07-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_buku_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='perpustakaan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buku_perpustakaan', to='api.perpustakaan'),
        ),
    ]
