# Generated by Django 5.2.4 on 2025-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_buku_perpustakaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='ID',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='ID',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perpustakaan',
            name='ID',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
