# Generated by Django 5.2.4 on 2025-07-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buku_id_genre_id_perpustakaan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='ID',
            new_name='bookID',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='ID',
            new_name='genreID',
        ),
        migrations.RenameField(
            model_name='perpustakaan',
            old_name='ID',
            new_name='libraryID',
        ),
    ]
