# Generated by Django 5.2.4 on 2025-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_id_buku_bookid_rename_id_genre_genreid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genreID',
        ),
        migrations.RemoveField(
            model_name='perpustakaan',
            name='libraryID',
        ),
    ]
